version: '3.8'
services:
  db:
    image: postgres:17
    container_name: employee_postgres
    environment:
      POSTGRES_DB: local-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "15432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d local-db"]
      interval: 5s
      retries: 5

  app:
    image: nemanja/employee-service
    container_name: employee_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/local-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
